### PR TITLE
Several improvements in setup.py

### PR DESCRIPTION
**Pull request by Mic92**
preparation for python3 support.

### CODE REVIEW

**Comment by rhelmot** [comment]
Very good! Thanks!

**Comment by Mic92** [comment]
Why is the majority of your travis ci build matrix broken?

**Comment by Mic92** [comment]
Why is the majority of your travis ci build matrix broken?

**Comment by ltfish** [comment]
Because we didn't have enough time to fix them.

**Comment by zardus** [comment]
We're currently undertaking a big refactor, and merged some things into
master that, in retrospect, weren't quite ready. We're working to fix them
as fast as we can, but academic deadlines have been taking up quite a lot
of time. Luckily, we (for sure, me) should be able to spend more time for
this in the near future.

Sorry to let you down with the matrix :-)

**Pull request merged**
