### PR TITLE
[WIP] travis: run unittests of this project

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by rhelmot** [comment]
So, uh, we know what we're doing testing wise. 

- the `tests` directory for pyvex is completely broken and out of date and reflects a version of pyvex at least three major versions out of date
- We must run the rest of the angr test suite on pushes to pyvex since these repositories depend on pyvex and it is important we not break them
- Specifying the Python language tag for Travis installs virtualenv in a way that is incompatible with our testing scripts

In the future, please pitch these sort of changes in an issue or discuss them on the angr slack before you sink time into them.

**Comment by zardus** [comment]
I'm not sure I'd say we *know* what we're doing, but we do tend to carry out a random walk with a tendency to go in the right direction. @rhelmot is absolute right: we need to run the rest of the suite, and, in essence, the only testcases we currently have for pyvex are the ones in the rest of angr (with the sole exception of `test_arm_postprocess.py`.

@Mic92, a `test.py` for pyvex that actually tests stuff (and isn't years out of date) would be an extremely-appreciated PR, if improving testing is something you're interested in. We're working on the rest of the test matrix, and with the pyvex tests added, we'll have quite a bit of green statuses!

**Comment by Mic92** [comment]
From my perspective it seems the current test actually tests the current branch and not the pull request: https://travis-ci.org/angr/pyvex/jobs/263927724#L631

Is this correct?

**Comment by rhelmot** [comment]
Nah, it runs on the current pull request. At the end of the setup phase it prints out a listing of every commit that every repository's HEAD is currently at, and you can see for pyvex:

```
############################## RUNNING ON: pyvex ###############################
commit 48fd734240c641d717724d9d3b7f582e50125d58 (HEAD)
Merge: 2df892e e6285bb
Author: Jörg Thalheim <Mic92@users.noreply.github.com>
Date:   Sat Aug 12 22:17:51 2017 +0000
    Merge e6285bb791d6d2f5da354e9def8fbe775aec0243 into 2df892e09c342032e07edd6d61d08809c7f26f1c
```

We are testing your pull request.

**Pull request closed without merging**
