### PR TITLE
OSSFuzz Integration

### PR DESCRIPTION
**Pull request by capuanob**
Hello!

I contributed to angr for my master's thesis and, having gotten deeper into fuzzing, thought to integrate pyvex into OSS Fuzz!

This PR introduces the source for the fuzzer and a YAML config to fuzz each PR for a set duration. I would greatly appreciate it being merged in! 

I will continue monitoring OSS-Fuzz for bugs and fix any I can in future PRs. Yan also has access to the OSS Fuzz dashboard to review any security-relevant crashes that may come up.

Please let me know if anything else is needed

### CODE REVIEW

**Comment by ltfish** [comment]
Hi @capuanob , thanks for your contribution!

I wonder why you decide to (use OSSFuzz to) fuzz pyvex instead of libVEX in Valgrind. Thoughts?

**Comment by twizmwazin** [comment]
It is not obvious to me how the pipeline description translates into the steps I see being done in the log. Is this process stored elsewhere? If we make changes in the future that would require tweaking the dependencies and install process, how would we go about keeping it working?

**Comment by capuanob** [comment]
The remainder of the configuration can be seen on the OSSFuzz project in
the projects/pyvex directory. Should there be a breaking change to the
build process, an alert would go out that the nightly OSS-Fuzz building has
failed for N (I believe three?) successive days. It would then require a PR
to update the build.sh in that project to reflect the new install process.

**Comment by capuanob** [comment]
To note, I will also get notifications and will try to maintain successful
fuzzing on the projects that are tied to my email.

**Comment by twizmwazin** [comment]
Gotcha. It seems the files in `fuzzing` are duplicated with the code in the oss-fuzz repo. Is that intentional? Which ones are actually being used?

**Comment by capuanob** [comment]
Currently, the ones in the OSS-Fuzz project. Once this gets merged, I will
switch it over. Didn't want to have downtime in fuzzing, but hosting it
here is preferred by Google and will allow for easier updates (more
harnessing or changes to existing fuzzers) than requiring PRs to OSS-Fuzz.

**Comment by twizmwazin** [comment]
In that case, would it be possible to also move the build process to this repo? And if someone makes a change that causes the harness to break, would the CI fail so we can fix it?

**Comment by capuanob** [comment]
As I understand it, the build.sh, Dockerfile, and project.Yaml must reside
in oss-fuzz.

I could think it would be possible to have build.sh call another bash
script for build instructions, but it would take some experimentation.

If possible, I’d appreciate if we could merge this in first and then I can
look into that once it’s working again

Thank You, Bailey Capuano

**Comment by capuanob** [comment]
> In that case, would it be possible to also move the build process to this repo? And if someone makes a change that causes the harness to break, would the CI fail so we can fix it?

As to the second question,

Should the harness be changed in a way that makes it exit instantly or unable to be called, the CI will fail when building as it tests to ensure that it can fuzz for a few iterations

**Comment by capuanob** [comment]
@twizmwazin I've looked into your question a bit more. The Dockerfile and project.yaml must be hosted in the OSS-Fuzz project. However, we could move the build.sh into the pyvex source. I'll push that up momentarily.

**Comment by capuanob** [comment]
@ltfish @twizmwazin Where does this PR stand? Is anything else needed for approval?

Thank you for your time in reviewing!

**Pull request merged**
