### PR TITLE
Improve Instruction class

### PR DESCRIPTION
**Pull request by ulugbekna**
Commits describe the contents of the PR.

### CODE REVIEW

**Comment by rhelmot** [comment]
lgtm so far

**Comment by ulugbekna** [comment]
Interesting, dfd9528217f4e7c9221f87c6df0fb98fc9880a49 breaks some code (but not tests) in a non-obvious way. I should probably remove it. For more context: I'm trying to extend angr to lift ebpf bytecode and have a small test file to create a project and lift the binary. But the failure below is more about registering archs at the beginning of angr startup not related to what I'm doing with ebpf. 

```python
Traceback (most recent call last):
  File "/Users/ulugbekna/code/semproj/angr-platforms/tests/test_ebpf.py", line 4, in <module>
    import angr
  File "/Users/ulugbekna/code/semproj/angr-dev/angr/angr/__init__.py", line 40, in <module>
    from .sim_procedure import SimProcedure
  File "/Users/ulugbekna/code/semproj/angr-dev/angr/angr/sim_procedure.py", line 6, in <module>
    from cle import SymbolType
  File "/Users/ulugbekna/code/semproj/angr-dev/cle/cle/__init__.py", line 18, in <module>
    from .loader import *
  File "/Users/ulugbekna/code/semproj/angr-dev/cle/cle/loader.py", line 8, in <module>
    import archinfo
  File "/Users/ulugbekna/code/semproj/angr-dev/archinfo/archinfo/__init__.py", line 26, in <module>
    from .arch_amd64    import ArchAMD64
  File "/Users/ulugbekna/code/semproj/angr-dev/archinfo/archinfo/arch_amd64.py", line 359, in <module>
    register_arch([r'.*amd64|.*x64|.*x86_64|.*metapc'], 64, Endness.LE, ArchAMD64)
  File "/Users/ulugbekna/code/semproj/angr-dev/archinfo/archinfo/arch.py", line 805, in register_arch
    all_arches.append(my_arch(endness))
  File "/Users/ulugbekna/code/semproj/angr-dev/archinfo/archinfo/arch_amd64.py", line 46, in __init__
    self.registers['rdi'][0]: 0,
KeyError: 'rdi'
```

**Comment by rhelmot** [comment]
Getting the following rst errors for the docstring:

```
/__w/1/s/build/src/pyvex/pyvex/lifting/util/instr_helper.py:docstring of pyvex.lifting.util.instr_helper.Instruction:19: WARNING: Unexpected indentation.
/__w/1/s/build/src/pyvex/pyvex/lifting/util/instr_helper.py:docstring of pyvex.lifting.util.instr_helper.Instruction:17: WARNING: Inline literal start-string without end-string.
/__w/1/s/build/src/pyvex/pyvex/lifting/util/instr_helper.py:docstring of pyvex.lifting.util.instr_helper.Instruction:22: WARNING: Block quote ends without a blank line; unexpected unindent.
/__w/1/s/build/src/pyvex/pyvex/lifting/util/instr_helper.py:docstring of pyvex.lifting.util.instr_helper.Instruction:22: WARNING: Inline literal start-string without end-string.
/__w/1/s/build/src/pyvex/pyvex/lifting/util/instr_helper.py:docstring of pyvex.lifting.util.instr_helper.Instruction:22: WARNING: Inline interpreted text or phrase reference start-string without end-string.
```

And the following lint errors:

```
LINT FAILURE: pyvex/lifting/util/instr_helper.py regressed to 9.13/9.42
... pyvex/lifting/util/instr_helper.py:298:79: C0303: Trailing whitespace (trailing-whitespace)
... pyvex/lifting/util/instr_helper.py:127:8: E1111: Assigning result of a function call, where the function has no return (assignment-from-no-return)
... pyvex/lifting/util/instr_helper.py:143:8: W0107: Unnecessary pass statement (unnecessary-pass)
... pyvex/lifting/util/instr_helper.py:157:8: W0107: Unnecessary pass statement (unnecessary-pass)
... pyvex/lifting/util/instr_helper.py:165:8: W0107: Unnecessary pass statement (unnecessary-pass)
... pyvex/lifting/util/instr_helper.py:379:8: C0415: Import outside toplevel (angr.engines.vex.claripy.ccall) (import-outside-toplevel)
... pyvex/lifting/util/instr_helper.py:400:4: R0201: Method could be a function (no-self-use)
... pyvex/lifting/util/instr_helper.py:4:0: C0411: standard import "import logging" should be placed before "import bitstring" (wrong-import-order)
```

**Comment by rhelmot** [comment]
For the lint errors, pylint with [this](https://github.com/angr/angr-dev/blob/master/pylintrc) config file. For the rst errors, clone angr-doc and then run run `make clean && make html` in the api-doc folder.

**Comment by rhelmot** [comment]
You will need to be in your angr virtualenv, with the following additional dependencies: `pip install sphinx sphinx_rtd_theme recommonmark`

**Comment by ulugbekna** [comment]
Hi, I made some more improvements to the `Instruction` class, fixed pylint complaints or muted them because they're not very correct for functions that are expected to be overridden. I really tried to fix sphynx errors, but they're cryptic, do not show what specific problems there are, so I gave up.

**Comment by rhelmot** [comment]
I pushed a fix for the rst errors. However, there seem to be a lot more additional CI failures now.

**Comment by ulugbekna** [comment]
Thanks! Indeed, there're some tests failing because of the changes in the PR. I'll try addressing them this week.

**Comment by ulugbekna** [comment]
Any idea why this one test case can be exceeding time limit?

**Comment by rhelmot** [comment]
It's a spurious failure :) I reran it and it passed.

Thanks!

**Pull request merged**
